
// april 2023, for example
d = [] // routingDict here

y = YAWNShowNew(d, Blast,Chaos,Lachrymator,CafeSara,Cement,Tokamak );

y.addCue( 'startShow', y. ) // need to make this class...
// blast stuff here...
y.addCue( 'startChaos', Chaos.cueFrom('count','elevenLast') )
y.addLoopCue( 'elevenLoopOne' )
y.addLoopCue( 'elevenLoopTwo' )
y.addCue( 'startBomb', Chaos.cueFrom('bomb','bomb') )
y.addCue( 'startChaosOutro, Chaos.cueFrom('countAgain','outro') )



y.addCue( Show.cueFrom('welcomeVoice','welcomeVoice') ) // need to make this class...





YAWNShowNew.april23

